#!/bin/bash

APPS=(
  "client"
  "server"
  "ide"
)

app=$(printf "%s\n" "${APPS[@]}" | gum choose)

echo "entering $app shell"

if [[ $app == "ide" ]]; then
  eval "nix develop"
else
  eval "nix develop .#$app"
fi
